<?php

use Illuminate\Database\Seeder;

class PostsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('posts')->delete();
        
        \DB::table('posts')->insert(array (
            0 => 
            array (
                'id' => 1,
                'title' => '3588323E-1E60-8ADA-1147-19012E129E8E',
                'slug' => '3588323e-1e60-8ada-1147-19012e129e8e',
                'hasTitle' => 0,
                'isGuest' => 1,
                'template_id' => '447',
                'user_id' => 1,
                'body' => NULL,
                'image' => '3588323E-1E60-8ADA-1147-19012E129E8E.png',
                'isPublished' => 0,
                'source' => NULL,
                'website' => NULL,
                'created_at' => '2019-03-01 09:36:44',
                'updated_at' => '2019-03-01 09:36:44',
            ),
            1 => 
            array (
                'id' => 2,
                'title' => 'A7543CAC-37A1-4225-146B-8051AC39CAFE',
                'slug' => 'a7543cac-37a1-4225-146b-8051ac39cafe',
                'hasTitle' => 0,
                'isGuest' => 1,
                'template_id' => '458',
                'user_id' => 1,
                'body' => NULL,
                'image' => 'A7543CAC-37A1-4225-146B-8051AC39CAFE.png',
                'isPublished' => 0,
                'source' => NULL,
                'website' => NULL,
                'created_at' => '2019-03-01 09:37:13',
                'updated_at' => '2019-03-01 09:37:13',
            ),
            2 => 
            array (
                'id' => 3,
                'title' => 'B9501417-F9D4-4E82-A9D3-4FDAD1AC41A9',
                'slug' => 'b9501417-f9d4-4e82-a9d3-4fdad1ac41a9',
                'hasTitle' => 0,
                'isGuest' => 1,
                'template_id' => NULL,
                'user_id' => 1,
                'body' => NULL,
                'image' => 'B9501417-F9D4-4E82-A9D3-4FDAD1AC41A9.png',
                'isPublished' => 0,
                'source' => NULL,
                'website' => NULL,
                'created_at' => '2019-03-01 09:37:31',
                'updated_at' => '2019-03-01 09:37:31',
            ),
            3 => 
            array (
                'id' => 4,
                'title' => 'F375FE3D-4C79-B08A-266B-4C64D73F1629',
                'slug' => 'f375fe3d-4c79-b08a-266b-4c64d73f1629',
                'hasTitle' => 0,
                'isGuest' => 1,
                'template_id' => '488',
                'user_id' => 1,
                'body' => NULL,
                'image' => 'F375FE3D-4C79-B08A-266B-4C64D73F1629.png',
                'isPublished' => 0,
                'source' => NULL,
                'website' => NULL,
                'created_at' => '2019-03-01 09:37:43',
                'updated_at' => '2019-03-01 09:37:43',
            ),
            4 => 
            array (
                'id' => 5,
                'title' => '2A1FD786-4121-4AB4-7317-B6C39C97B326',
                'slug' => '2a1fd786-4121-4ab4-7317-b6c39c97b326',
                'hasTitle' => 0,
                'isGuest' => 1,
                'template_id' => '103',
                'user_id' => 1,
                'body' => NULL,
                'image' => '2A1FD786-4121-4AB4-7317-B6C39C97B326.png',
                'isPublished' => 0,
                'source' => NULL,
                'website' => NULL,
                'created_at' => '2019-03-01 09:38:01',
                'updated_at' => '2019-03-01 09:38:01',
            ),
            5 => 
            array (
                'id' => 6,
                'title' => 'ECE7F825-B55E-16EB-6806-FFDA2C6C3B55',
                'slug' => 'ece7f825-b55e-16eb-6806-ffda2c6c3b55',
                'hasTitle' => 0,
                'isGuest' => 1,
                'template_id' => '103',
                'user_id' => NULL,
                'body' => NULL,
                'image' => 'ECE7F825-B55E-16EB-6806-FFDA2C6C3B55.png',
                'isPublished' => 0,
                'source' => NULL,
                'website' => NULL,
                'created_at' => '2019-03-01 09:38:44',
                'updated_at' => '2019-03-01 09:38:44',
            ),
            6 => 
            array (
                'id' => 7,
                'title' => '46B697B0-2739-1FF9-B937-40233C69E288',
                'slug' => '46b697b0-2739-1ff9-b937-40233c69e288',
                'hasTitle' => 0,
                'isGuest' => 1,
                'template_id' => NULL,
                'user_id' => NULL,
                'body' => NULL,
                'image' => '46B697B0-2739-1FF9-B937-40233C69E288.png',
                'isPublished' => 0,
                'source' => NULL,
                'website' => NULL,
                'created_at' => '2019-03-01 09:38:57',
                'updated_at' => '2019-03-01 09:38:57',
            ),
            7 => 
            array (
                'id' => 8,
                'title' => 'D9C8B839-AFBA-30C3-C2A7-C51C41487761',
                'slug' => 'd9c8b839-afba-30c3-c2a7-c51c41487761',
                'hasTitle' => 0,
                'isGuest' => 1,
                'template_id' => NULL,
                'user_id' => NULL,
                'body' => NULL,
                'image' => 'D9C8B839-AFBA-30C3-C2A7-C51C41487761.gif',
                'isPublished' => 0,
                'source' => NULL,
                'website' => NULL,
                'created_at' => '2019-03-01 09:39:18',
                'updated_at' => '2019-03-01 09:39:18',
            ),
            8 => 
            array (
                'id' => 9,
                'title' => '6B18C0C1-36FB-24DA-E326-10B9C94EEA54',
                'slug' => '6b18c0c1-36fb-24da-e326-10b9c94eea54',
                'hasTitle' => 0,
                'isGuest' => 1,
                'template_id' => '458',
                'user_id' => NULL,
                'body' => NULL,
                'image' => '6B18C0C1-36FB-24DA-E326-10B9C94EEA54.png',
                'isPublished' => 0,
                'source' => NULL,
                'website' => NULL,
                'created_at' => '2019-03-01 09:39:46',
                'updated_at' => '2019-03-01 09:39:46',
            ),
            9 => 
            array (
                'id' => 10,
                'title' => 'Wait. That’s Illegal',
                'slug' => 'wait-thats-illegal',
                'hasTitle' => 0,
                'isGuest' => 0,
                'template_id' => NULL,
                'user_id' => 11,
                'body' => NULL,
                'image' => 'qbkdn2ii7dj21.jpg',
                'isPublished' => 1,
                'source' => 'https://i.redd.it/qbkdn2ii7dj21.jpg',
                'website' => 'reddit',
                'created_at' => '2019-03-01 09:43:23',
                'updated_at' => '2019-03-01 09:43:23',
            ),
            10 => 
            array (
                'id' => 11,
                'title' => 'Do You Understand The Words Coming Out Of My Mouth? No. I Don\'t.',
                'slug' => 'do-you-understand-the-words-coming-out-of-my-mouth-no-i-dont',
                'hasTitle' => 0,
                'isGuest' => 0,
                'template_id' => NULL,
                'user_id' => 12,
                'body' => NULL,
                'image' => 'fraj7zli8bj21.jpg',
                'isPublished' => 1,
                'source' => 'https://i.redd.it/fraj7zli8bj21.jpg',
                'website' => 'reddit',
                'created_at' => '2019-03-01 09:43:25',
                'updated_at' => '2019-03-01 09:43:25',
            ),
            11 => 
            array (
                'id' => 12,
                'title' => 'For Real Tho',
                'slug' => 'for-real-tho',
                'hasTitle' => 0,
                'isGuest' => 0,
                'template_id' => NULL,
                'user_id' => 14,
                'body' => NULL,
                'image' => '5r815gxdqej21.jpg',
                'isPublished' => 1,
                'source' => 'https://i.redd.it/5r815gxdqej21.jpg',
                'website' => 'reddit',
                'created_at' => '2019-03-01 09:43:27',
                'updated_at' => '2019-03-01 09:43:27',
            ),
            12 => 
            array (
                'id' => 13,
                'title' => 'IGNorant',
                'slug' => 'ignorant',
                'hasTitle' => 0,
                'isGuest' => 0,
                'template_id' => NULL,
                'user_id' => 14,
                'body' => NULL,
                'image' => 'kd50hjz9hcj21.jpg',
                'isPublished' => 1,
                'source' => 'https://i.redd.it/kd50hjz9hcj21.jpg',
                'website' => 'reddit',
                'created_at' => '2019-03-01 09:43:29',
                'updated_at' => '2019-03-01 09:43:29',
            ),
            13 => 
            array (
                'id' => 14,
                'title' => 'Well Look Who Decided To Join Us',
                'slug' => 'well-look-who-decided-to-join-us',
                'hasTitle' => 0,
                'isGuest' => 0,
                'template_id' => NULL,
                'user_id' => 10,
                'body' => NULL,
                'image' => 'uf7x77ll7aj21.jpg',
                'isPublished' => 1,
                'source' => 'https://i.redd.it/uf7x77ll7aj21.jpg',
                'website' => 'reddit',
                'created_at' => '2019-03-01 09:43:30',
                'updated_at' => '2019-03-01 09:43:30',
            ),
            14 => 
            array (
                'id' => 15,
                'title' => 'I\'m Good, Other Than I Kill People',
                'slug' => 'im-good-other-than-i-kill-people',
                'hasTitle' => 0,
                'isGuest' => 0,
                'template_id' => NULL,
                'user_id' => 5,
                'body' => NULL,
                'image' => '9f6s9czmbbj21.jpg',
                'isPublished' => 1,
                'source' => 'https://i.redd.it/9f6s9czmbbj21.jpg',
                'website' => 'reddit',
                'created_at' => '2019-03-01 09:43:33',
                'updated_at' => '2019-03-01 09:43:33',
            ),
            15 => 
            array (
                'id' => 16,
                'title' => 'This Template Could Actually Work',
                'slug' => 'this-template-could-actually-work',
                'hasTitle' => 0,
                'isGuest' => 0,
                'template_id' => NULL,
                'user_id' => 3,
                'body' => NULL,
                'image' => '81r67vfyeaj21.jpg',
                'isPublished' => 1,
                'source' => 'https://i.redd.it/81r67vfyeaj21.jpg',
                'website' => 'reddit',
                'created_at' => '2019-03-01 09:43:36',
                'updated_at' => '2019-03-01 09:43:36',
            ),
            16 => 
            array (
                'id' => 17,
                'title' => 'Too Much Adderall, Too Little Sleep',
                'slug' => 'too-much-adderall-too-little-sleep',
                'hasTitle' => 0,
                'isGuest' => 0,
                'template_id' => NULL,
                'user_id' => 23,
                'body' => NULL,
                'image' => 'ovcj9kypdbj21.jpg',
                'isPublished' => 1,
                'source' => 'https://i.redd.it/ovcj9kypdbj21.jpg',
                'website' => 'reddit',
                'created_at' => '2019-03-01 09:43:38',
                'updated_at' => '2019-03-01 09:43:38',
            ),
            17 => 
            array (
                'id' => 18,
                'title' => 'This Is How You Recover',
                'slug' => 'this-is-how-you-recover',
                'hasTitle' => 0,
                'isGuest' => 0,
                'template_id' => NULL,
                'user_id' => 12,
                'body' => NULL,
                'image' => '6lhz16qh1bj21.jpg',
                'isPublished' => 1,
                'source' => 'https://i.redd.it/6lhz16qh1bj21.jpg',
                'website' => 'reddit',
                'created_at' => '2019-03-01 09:43:40',
                'updated_at' => '2019-03-01 09:43:40',
            ),
            18 => 
            array (
                'id' => 19,
                'title' => 'I Don\'t Know Just Pay',
                'slug' => 'i-dont-know-just-pay',
                'hasTitle' => 0,
                'isGuest' => 0,
                'template_id' => NULL,
                'user_id' => 7,
                'body' => NULL,
                'image' => 'ulsn6dwfmbj21.png',
                'isPublished' => 1,
                'source' => 'https://i.redd.it/ulsn6dwfmbj21.png',
                'website' => 'reddit',
                'created_at' => '2019-03-01 09:43:45',
                'updated_at' => '2019-03-01 09:43:45',
            ),
            19 => 
            array (
                'id' => 20,
                'title' => 'Hey, Do You Know? Do Ya?',
                'slug' => 'hey-do-you-know-do-ya',
                'hasTitle' => 0,
                'isGuest' => 0,
                'template_id' => NULL,
                'user_id' => 21,
                'body' => NULL,
                'image' => 'iqy1r92w5bj21.jpg',
                'isPublished' => 1,
                'source' => 'https://i.redd.it/iqy1r92w5bj21.jpg',
                'website' => 'reddit',
                'created_at' => '2019-03-01 09:43:47',
                'updated_at' => '2019-03-01 09:43:47',
            ),
            20 => 
            array (
                'id' => 21,
                'title' => 'It Truly Do Be Like That',
                'slug' => 'it-truly-do-be-like-that',
                'hasTitle' => 0,
                'isGuest' => 0,
                'template_id' => NULL,
                'user_id' => 10,
                'body' => NULL,
                'image' => 'j4z5ps3vwaj21.jpg',
                'isPublished' => 1,
                'source' => 'https://i.redd.it/j4z5ps3vwaj21.jpg',
                'website' => 'reddit',
                'created_at' => '2019-03-01 09:43:49',
                'updated_at' => '2019-03-01 09:43:49',
            ),
            21 => 
            array (
                'id' => 22,
                'title' => 'Am I Right, Fellas?',
                'slug' => 'am-i-right-fellas',
                'hasTitle' => 0,
                'isGuest' => 0,
                'template_id' => NULL,
                'user_id' => 1,
                'body' => NULL,
                'image' => 'h7z74b6wzbj21.jpg',
                'isPublished' => 1,
                'source' => 'https://i.redd.it/h7z74b6wzbj21.jpg',
                'website' => 'reddit',
                'created_at' => '2019-03-01 09:43:51',
                'updated_at' => '2019-03-01 09:43:51',
            ),
            22 => 
            array (
                'id' => 23,
                'title' => 'A Hero Rises',
                'slug' => 'a-hero-rises',
                'hasTitle' => 0,
                'isGuest' => 0,
                'template_id' => NULL,
                'user_id' => 5,
                'body' => NULL,
                'image' => 'zmp1x1jnfaj21.jpg',
                'isPublished' => 1,
                'source' => 'https://i.redd.it/zmp1x1jnfaj21.jpg',
                'website' => 'reddit',
                'created_at' => '2019-03-01 09:43:53',
                'updated_at' => '2019-03-01 09:43:53',
            ),
            23 => 
            array (
                'id' => 24,
                'title' => 'We Don’t Deserve Him..',
                'slug' => 'we-dont-deserve-him',
                'hasTitle' => 0,
                'isGuest' => 0,
                'template_id' => NULL,
                'user_id' => 25,
                'body' => NULL,
                'image' => '3v8uvr8wycj21.jpg',
                'isPublished' => 1,
                'source' => 'https://i.redd.it/3v8uvr8wycj21.jpg',
                'website' => 'reddit',
                'created_at' => '2019-03-01 09:43:57',
                'updated_at' => '2019-03-01 09:43:57',
            ),
            24 => 
            array (
                'id' => 25,
                'title' => 'Give Me My Money Back',
                'slug' => 'give-me-my-money-back',
                'hasTitle' => 0,
                'isGuest' => 0,
                'template_id' => NULL,
                'user_id' => 7,
                'body' => NULL,
                'image' => '2axq06yd4bj21.jpg',
                'isPublished' => 1,
                'source' => 'https://i.redd.it/2axq06yd4bj21.jpg',
                'website' => 'reddit',
                'created_at' => '2019-03-01 09:43:58',
                'updated_at' => '2019-03-01 09:43:58',
            ),
            25 => 
            array (
                'id' => 26,
                'title' => 'BATTLE OF THE AGES',
                'slug' => 'battle-of-the-ages',
                'hasTitle' => 0,
                'isGuest' => 0,
                'template_id' => NULL,
                'user_id' => 4,
                'body' => NULL,
                'image' => 'w61kcvr2kcj21.jpg',
                'isPublished' => 1,
                'source' => 'https://i.redd.it/w61kcvr2kcj21.jpg',
                'website' => 'reddit',
                'created_at' => '2019-03-01 09:44:01',
                'updated_at' => '2019-03-01 09:44:01',
            ),
            26 => 
            array (
                'id' => 27,
                'title' => 'If Only All The Girls In School Were Like My Mother.',
                'slug' => 'if-only-all-the-girls-in-school-were-like-my-mother',
                'hasTitle' => 0,
                'isGuest' => 0,
                'template_id' => NULL,
                'user_id' => 1,
                'body' => NULL,
                'image' => 'ln12j5jb9bj21.jpg',
                'isPublished' => 1,
                'source' => 'https://i.redd.it/ln12j5jb9bj21.jpg',
                'website' => 'reddit',
                'created_at' => '2019-03-01 09:44:02',
                'updated_at' => '2019-03-01 09:44:02',
            ),
            27 => 
            array (
                'id' => 28,
                'title' => 'More Like Subtities',
                'slug' => 'more-like-subtities',
                'hasTitle' => 0,
                'isGuest' => 0,
                'template_id' => NULL,
                'user_id' => 16,
                'body' => NULL,
                'image' => 'ktqojkxr8bj21.jpg',
                'isPublished' => 1,
                'source' => 'https://i.redd.it/ktqojkxr8bj21.jpg',
                'website' => 'reddit',
                'created_at' => '2019-03-01 09:44:05',
                'updated_at' => '2019-03-01 09:44:05',
            ),
            28 => 
            array (
                'id' => 29,
                'title' => 'Bird Box Alternate Ending Revealed',
                'slug' => 'bird-box-alternate-ending-revealed',
                'hasTitle' => 0,
                'isGuest' => 0,
                'template_id' => NULL,
                'user_id' => 19,
                'body' => NULL,
                'image' => '2kdajoboaaj21.jpg',
                'isPublished' => 1,
                'source' => 'https://i.redd.it/2kdajoboaaj21.jpg',
                'website' => 'reddit',
                'created_at' => '2019-03-01 09:44:06',
                'updated_at' => '2019-03-01 09:44:06',
            ),
            29 => 
            array (
                'id' => 30,
                'title' => 'Vaccines Cause Autism Logic',
                'slug' => 'vaccines-cause-autism-logic',
                'hasTitle' => 0,
                'isGuest' => 0,
                'template_id' => NULL,
                'user_id' => 5,
                'body' => NULL,
                'image' => 'e97efhbr9dj21.jpg',
                'isPublished' => 1,
                'source' => 'https://i.redd.it/e97efhbr9dj21.jpg',
                'website' => 'reddit',
                'created_at' => '2019-03-01 09:44:08',
                'updated_at' => '2019-03-01 09:44:08',
            ),
            30 => 
            array (
                'id' => 31,
                'title' => 'A Little Change Up',
                'slug' => 'a-little-change-up',
                'hasTitle' => 0,
                'isGuest' => 0,
                'template_id' => NULL,
                'user_id' => 23,
                'body' => NULL,
                'image' => 'rpMNqFk.jpg',
                'isPublished' => 1,
                'source' => 'https://i.imgur.com/rpMNqFk.jpg',
                'website' => 'reddit',
                'created_at' => '2019-03-01 09:44:11',
                'updated_at' => '2019-03-01 09:44:11',
            ),
            31 => 
            array (
                'id' => 32,
                'title' => 'Very Wholesome Boys, Very Wholesome',
                'slug' => 'very-wholesome-boys-very-wholesome',
                'hasTitle' => 0,
                'isGuest' => 0,
                'template_id' => NULL,
                'user_id' => 25,
                'body' => NULL,
                'image' => 'yr350i1l4fj21.jpg',
                'isPublished' => 1,
                'source' => 'https://i.redd.it/yr350i1l4fj21.jpg',
                'website' => 'reddit',
                'created_at' => '2019-03-01 09:44:13',
                'updated_at' => '2019-03-01 09:44:13',
            ),
            32 => 
            array (
                'id' => 33,
                'title' => 'I\'m A Hero',
                'slug' => 'im-a-hero',
                'hasTitle' => 0,
                'isGuest' => 0,
                'template_id' => NULL,
                'user_id' => 16,
                'body' => NULL,
                'image' => 'x97m9w7bicj21.png',
                'isPublished' => 1,
                'source' => 'https://i.redd.it/x97m9w7bicj21.png',
                'website' => 'reddit',
                'created_at' => '2019-03-01 09:44:16',
                'updated_at' => '2019-03-01 09:44:16',
            ),
            33 => 
            array (
                'id' => 34,
                'title' => 'AHH FUCK, I CAN’T BELIEVE YOU’VE DONE THIS',
                'slug' => 'ahh-fuck-i-cant-believe-youve-done-this',
                'hasTitle' => 0,
                'isGuest' => 0,
                'template_id' => NULL,
                'user_id' => 22,
                'body' => NULL,
                'image' => 'ia2u3j6u2bj21.jpg',
                'isPublished' => 1,
                'source' => 'https://i.redd.it/ia2u3j6u2bj21.jpg',
                'website' => 'reddit',
                'created_at' => '2019-03-01 09:44:18',
                'updated_at' => '2019-03-01 09:44:18',
            ),
            34 => 
            array (
                'id' => 35,
                'title' => 'They\'ve Been Smeckledorfed!',
                'slug' => 'theyve-been-smeckledorfed',
                'hasTitle' => 0,
                'isGuest' => 0,
                'template_id' => NULL,
                'user_id' => 22,
                'body' => NULL,
                'image' => '7g4psvvwtbj21.jpg',
                'isPublished' => 1,
                'source' => 'https://i.redd.it/7g4psvvwtbj21.jpg',
                'website' => 'reddit',
                'created_at' => '2019-03-01 09:44:20',
                'updated_at' => '2019-03-01 09:44:20',
            ),
            35 => 
            array (
                'id' => 36,
                'title' => 'Shake And Bake',
                'slug' => 'shake-and-bake',
                'hasTitle' => 0,
                'isGuest' => 0,
                'template_id' => NULL,
                'user_id' => 14,
                'body' => NULL,
                'image' => '12u6vf53ucj21.jpg',
                'isPublished' => 1,
                'source' => 'https://i.redd.it/12u6vf53ucj21.jpg',
                'website' => 'reddit',
                'created_at' => '2019-03-01 09:44:21',
                'updated_at' => '2019-03-01 09:44:21',
            ),
            36 => 
            array (
                'id' => 37,
                'title' => 'Makes Sense',
                'slug' => 'makes-sense',
                'hasTitle' => 0,
                'isGuest' => 0,
                'template_id' => NULL,
                'user_id' => 16,
                'body' => NULL,
                'image' => 'rfzfjwe7icj21.jpg',
                'isPublished' => 1,
                'source' => 'https://i.redd.it/rfzfjwe7icj21.jpg',
                'website' => 'reddit',
                'created_at' => '2019-03-01 09:44:23',
                'updated_at' => '2019-03-01 09:44:23',
            ),
            37 => 
            array (
                'id' => 38,
                'title' => 'You Seem Very Nice',
                'slug' => 'you-seem-very-nice',
                'hasTitle' => 0,
                'isGuest' => 0,
                'template_id' => NULL,
                'user_id' => 1,
                'body' => NULL,
                'image' => '2gnymfag6dj21.png',
                'isPublished' => 1,
                'source' => 'https://i.redd.it/2gnymfag6dj21.png',
                'website' => 'reddit',
                'created_at' => '2019-03-01 09:44:25',
                'updated_at' => '2019-03-01 09:44:25',
            ),
            38 => 
            array (
                'id' => 39,
                'title' => 'Bargain',
                'slug' => 'bargain',
                'hasTitle' => 0,
                'isGuest' => 0,
                'template_id' => NULL,
                'user_id' => 21,
                'body' => NULL,
                'image' => '8t1rn3b21cj21.png',
                'isPublished' => 1,
                'source' => 'https://i.redd.it/8t1rn3b21cj21.png',
                'website' => 'reddit',
                'created_at' => '2019-03-01 09:44:28',
                'updated_at' => '2019-03-01 09:44:28',
            ),
            39 => 
            array (
                'id' => 40,
                'title' => 'Curiously Killed The Cat.',
                'slug' => 'curiously-killed-the-cat',
                'hasTitle' => 0,
                'isGuest' => 0,
                'template_id' => NULL,
                'user_id' => 13,
                'body' => NULL,
                'image' => '6w2e303subj21.jpg',
                'isPublished' => 1,
                'source' => 'https://i.redd.it/6w2e303subj21.jpg',
                'website' => 'reddit',
                'created_at' => '2019-03-01 09:44:29',
                'updated_at' => '2019-03-01 09:44:29',
            ),
            40 => 
            array (
                'id' => 41,
                'title' => 'Yeaaaah',
                'slug' => 'yeaaaah',
                'hasTitle' => 0,
                'isGuest' => 0,
                'template_id' => NULL,
                'user_id' => 23,
                'body' => NULL,
                'image' => '2g0n9hz1cej21.jpg',
                'isPublished' => 1,
                'source' => 'https://i.redd.it/2g0n9hz1cej21.jpg',
                'website' => 'reddit',
                'created_at' => '2019-03-01 09:44:31',
                'updated_at' => '2019-03-01 09:44:31',
            ),
            41 => 
            array (
                'id' => 42,
                'title' => 'OC Trash Meme',
                'slug' => 'oc-trash-meme',
                'hasTitle' => 0,
                'isGuest' => 0,
                'template_id' => NULL,
                'user_id' => 14,
                'body' => NULL,
                'image' => '05nwc2dx6bj21.png',
                'isPublished' => 1,
                'source' => 'https://i.redd.it/05nwc2dx6bj21.png',
                'website' => 'reddit',
                'created_at' => '2019-03-01 09:44:34',
                'updated_at' => '2019-03-01 09:44:34',
            ),
            42 => 
            array (
                'id' => 43,
                'title' => 'Run! He\'s Ducking Crazy!',
                'slug' => 'run-hes-ducking-crazy',
                'hasTitle' => 0,
                'isGuest' => 0,
                'template_id' => NULL,
                'user_id' => 16,
                'body' => NULL,
                'image' => '8ehr28u6kbj21.jpg',
                'isPublished' => 1,
                'source' => 'https://i.redd.it/8ehr28u6kbj21.jpg',
                'website' => 'reddit',
                'created_at' => '2019-03-01 09:44:36',
                'updated_at' => '2019-03-01 09:44:36',
            ),
            43 => 
            array (
                'id' => 44,
                'title' => 'Me Right Now',
                'slug' => 'me-right-now',
                'hasTitle' => 0,
                'isGuest' => 0,
                'template_id' => NULL,
                'user_id' => 17,
                'body' => NULL,
                'image' => 'pmplxqet5dj21.png',
                'isPublished' => 1,
                'source' => 'https://i.redd.it/pmplxqet5dj21.png',
                'website' => 'reddit',
                'created_at' => '2019-03-01 09:44:38',
                'updated_at' => '2019-03-01 09:44:38',
            ),
            44 => 
            array (
                'id' => 45,
                'title' => 'R/incel',
                'slug' => 'rincel',
                'hasTitle' => 0,
                'isGuest' => 0,
                'template_id' => NULL,
                'user_id' => 14,
                'body' => NULL,
                'image' => 'xm5snfoqzej21.jpg',
                'isPublished' => 1,
                'source' => 'https://i.redd.it/xm5snfoqzej21.jpg',
                'website' => 'reddit',
                'created_at' => '2019-03-01 09:44:40',
                'updated_at' => '2019-03-01 09:44:40',
            ),
            45 => 
            array (
                'id' => 46,
                'title' => 'This Generation Is Getting Out Of Control',
                'slug' => 'this-generation-is-getting-out-of-control',
                'hasTitle' => 0,
                'isGuest' => 0,
                'template_id' => NULL,
                'user_id' => 11,
                'body' => NULL,
                'image' => 'ai99q63sxcj21.jpg',
                'isPublished' => 1,
                'source' => 'https://i.redd.it/ai99q63sxcj21.jpg',
                'website' => 'reddit',
                'created_at' => '2019-03-01 09:44:41',
                'updated_at' => '2019-03-01 09:44:41',
            ),
            46 => 
            array (
                'id' => 47,
                'title' => 'Ever Heard About The Mighty French Battles, Yeah Me Neither',
                'slug' => 'ever-heard-about-the-mighty-french-battles-yeah-me-neither',
                'hasTitle' => 0,
                'isGuest' => 0,
                'template_id' => NULL,
                'user_id' => 20,
                'body' => NULL,
                'image' => 'anrsm7tm7cj21.jpg',
                'isPublished' => 1,
                'source' => 'https://i.redd.it/anrsm7tm7cj21.jpg',
                'website' => 'reddit',
                'created_at' => '2019-03-01 09:44:43',
                'updated_at' => '2019-03-01 09:44:43',
            ),
            47 => 
            array (
                'id' => 48,
                'title' => 'Stop Digging',
                'slug' => 'stop-digging',
                'hasTitle' => 0,
                'isGuest' => 0,
                'template_id' => NULL,
                'user_id' => 18,
                'body' => NULL,
                'image' => 'xmpmpa5h4aj21.jpg',
                'isPublished' => 1,
                'source' => 'https://i.redd.it/xmpmpa5h4aj21.jpg',
                'website' => 'reddit',
                'created_at' => '2019-03-01 09:44:45',
                'updated_at' => '2019-03-01 09:44:45',
            ),
            48 => 
            array (
                'id' => 49,
                'title' => 'Well I\'d Definitely Like To See You Try.',
                'slug' => 'well-id-definitely-like-to-see-you-try',
                'hasTitle' => 0,
                'isGuest' => 0,
                'template_id' => NULL,
                'user_id' => 9,
                'body' => NULL,
                'image' => '46vonnb7cej21.png',
                'isPublished' => 1,
                'source' => 'https://i.redd.it/46vonnb7cej21.png',
                'website' => 'reddit',
                'created_at' => '2019-03-01 09:44:47',
                'updated_at' => '2019-03-01 09:44:47',
            ),
            49 => 
            array (
                'id' => 50,
                'title' => 'There Is No Rules!',
                'slug' => 'there-is-no-rules',
                'hasTitle' => 0,
                'isGuest' => 0,
                'template_id' => NULL,
                'user_id' => 21,
                'body' => NULL,
                'image' => 'vfmls4p8gej21.jpg',
                'isPublished' => 1,
                'source' => 'https://i.redd.it/vfmls4p8gej21.jpg',
                'website' => 'reddit',
                'created_at' => '2019-03-01 09:44:48',
                'updated_at' => '2019-03-01 09:44:48',
            ),
            50 => 
            array (
                'id' => 51,
                'title' => 'Found This Meme, Had To Fix It',
                'slug' => 'found-this-meme-had-to-fix-it',
                'hasTitle' => 0,
                'isGuest' => 0,
                'template_id' => NULL,
                'user_id' => 9,
                'body' => NULL,
                'image' => 'kk18p4ap9cj21.jpg',
                'isPublished' => 1,
                'source' => 'https://i.redd.it/kk18p4ap9cj21.jpg',
                'website' => 'reddit',
                'created_at' => '2019-03-01 09:44:50',
                'updated_at' => '2019-03-01 09:44:50',
            ),
            51 => 
            array (
                'id' => 52,
                'title' => 'Made Me Chuckle',
                'slug' => 'made-me-chuckle',
                'hasTitle' => 0,
                'isGuest' => 0,
                'template_id' => NULL,
                'user_id' => 10,
                'body' => NULL,
                'image' => 'v6gineimwfj21.jpg',
                'isPublished' => 1,
                'source' => 'https://i.redd.it/v6gineimwfj21.jpg',
                'website' => 'reddit',
                'created_at' => '2019-03-01 09:44:52',
                'updated_at' => '2019-03-01 09:44:52',
            ),
            52 => 
            array (
                'id' => 53,
                'title' => 'Happened To Me Today',
                'slug' => 'happened-to-me-today',
                'hasTitle' => 0,
                'isGuest' => 0,
                'template_id' => NULL,
                'user_id' => 7,
                'body' => NULL,
                'image' => '11bt0u82bfj21.jpg',
                'isPublished' => 1,
                'source' => 'https://i.redd.it/11bt0u82bfj21.jpg',
                'website' => 'reddit',
                'created_at' => '2019-03-01 09:44:53',
                'updated_at' => '2019-03-01 09:44:53',
            ),
            53 => 
            array (
                'id' => 54,
                'title' => 'Heaven Is Waiting',
                'slug' => 'heaven-is-waiting',
                'hasTitle' => 0,
                'isGuest' => 0,
                'template_id' => NULL,
                'user_id' => 11,
                'body' => NULL,
                'image' => 'udms2fbx1bj21.jpg',
                'isPublished' => 1,
                'source' => 'https://i.redd.it/udms2fbx1bj21.jpg',
                'website' => 'reddit',
                'created_at' => '2019-03-01 09:44:54',
                'updated_at' => '2019-03-01 09:44:54',
            ),
            54 => 
            array (
                'id' => 55,
                'title' => 'The Boys Exist In Both Yards Simultaneously',
                'slug' => 'the-boys-exist-in-both-yards-simultaneously',
                'hasTitle' => 0,
                'isGuest' => 0,
                'template_id' => NULL,
                'user_id' => 5,
                'body' => NULL,
                'image' => 'wqs1ih7jyej21.jpg',
                'isPublished' => 1,
                'source' => 'https://i.redd.it/wqs1ih7jyej21.jpg',
                'website' => 'reddit',
                'created_at' => '2019-03-01 09:44:56',
                'updated_at' => '2019-03-01 09:44:56',
            ),
            55 => 
            array (
                'id' => 56,
                'title' => 'Calculator Meme',
                'slug' => 'calculator-meme',
                'hasTitle' => 0,
                'isGuest' => 0,
                'template_id' => NULL,
                'user_id' => 5,
                'body' => NULL,
                'image' => 'xyitiey21bj21.jpg',
                'isPublished' => 1,
                'source' => 'https://i.redd.it/xyitiey21bj21.jpg',
                'website' => 'reddit',
                'created_at' => '2019-03-01 09:44:58',
                'updated_at' => '2019-03-01 09:44:58',
            ),
            56 => 
            array (
                'id' => 57,
                'title' => 'How Did This Happen?',
                'slug' => 'how-did-this-happen',
                'hasTitle' => 0,
                'isGuest' => 0,
                'template_id' => NULL,
                'user_id' => 8,
                'body' => NULL,
                'image' => 'mb0uahvfnfj21.jpg',
                'isPublished' => 1,
                'source' => 'https://i.redd.it/mb0uahvfnfj21.jpg',
                'website' => 'reddit',
                'created_at' => '2019-03-01 09:45:00',
                'updated_at' => '2019-03-01 09:45:00',
            ),
            57 => 
            array (
                'id' => 58,
                'title' => 'Jajajaja',
                'slug' => 'jajajaja',
                'hasTitle' => 0,
                'isGuest' => 0,
                'template_id' => NULL,
                'user_id' => 14,
                'body' => NULL,
                'image' => '6gkcmd9k2dj21.jpg',
                'isPublished' => 1,
                'source' => 'https://i.redd.it/6gkcmd9k2dj21.jpg',
                'website' => 'reddit',
                'created_at' => '2019-03-01 09:45:02',
                'updated_at' => '2019-03-01 09:45:02',
            ),
            58 => 
            array (
                'id' => 59,
                'title' => '0723AB3F-3DE1-5486-B749-1507B55407ED',
                'slug' => '0723ab3f-3de1-5486-b749-1507b55407ed',
                'hasTitle' => 0,
                'isGuest' => 1,
                'template_id' => '34',
                'user_id' => NULL,
                'body' => NULL,
                'image' => '0723AB3F-3DE1-5486-B749-1507B55407ED.png',
                'isPublished' => 0,
                'source' => NULL,
                'website' => NULL,
                'created_at' => '2019-03-02 08:14:09',
                'updated_at' => '2019-03-02 08:14:09',
            ),
            59 => 
            array (
                'id' => 60,
                'title' => '7CE265C5-5F37-D696-6D96-10FDD01B0B1F',
                'slug' => '7ce265c5-5f37-d696-6d96-10fdd01b0b1f',
                'hasTitle' => 0,
                'isGuest' => 1,
                'template_id' => '336',
                'user_id' => NULL,
                'body' => NULL,
                'image' => '7CE265C5-5F37-D696-6D96-10FDD01B0B1F.png',
                'isPublished' => 0,
                'source' => NULL,
                'website' => NULL,
                'created_at' => '2019-03-04 08:48:08',
                'updated_at' => '2019-03-04 08:48:08',
            ),
            60 => 
            array (
                'id' => 61,
                'title' => '85DCD785-21C3-F171-597C-288A2256B2E5',
                'slug' => '85dcd785-21c3-f171-597c-288a2256b2e5',
                'hasTitle' => 0,
                'isGuest' => 1,
                'template_id' => '336',
                'user_id' => NULL,
                'body' => NULL,
                'image' => '85DCD785-21C3-F171-597C-288A2256B2E5.png',
                'isPublished' => 0,
                'source' => NULL,
                'website' => NULL,
                'created_at' => '2019-03-04 08:48:37',
                'updated_at' => '2019-03-04 08:48:37',
            ),
            61 => 
            array (
                'id' => 62,
                'title' => 'AFC85A8C-320A-9A6D-553C-9E58A755BAD0',
                'slug' => 'afc85a8c-320a-9a6d-553c-9e58a755bad0',
                'hasTitle' => 0,
                'isGuest' => 1,
                'template_id' => '336',
                'user_id' => NULL,
                'body' => NULL,
                'image' => 'AFC85A8C-320A-9A6D-553C-9E58A755BAD0.png',
                'isPublished' => 0,
                'source' => NULL,
                'website' => NULL,
                'created_at' => '2019-03-04 08:48:48',
                'updated_at' => '2019-03-04 08:48:48',
            ),
            62 => 
            array (
                'id' => 63,
                'title' => 'CFD76819-5025-E245-FCE8-AFC10322EA3F',
                'slug' => 'cfd76819-5025-e245-fce8-afc10322ea3f',
                'hasTitle' => 0,
                'isGuest' => 1,
                'template_id' => NULL,
                'user_id' => NULL,
                'body' => NULL,
                'image' => 'CFD76819-5025-E245-FCE8-AFC10322EA3F.png',
                'isPublished' => 0,
                'source' => NULL,
                'website' => NULL,
                'created_at' => '2019-03-08 09:41:03',
                'updated_at' => '2019-03-08 09:41:03',
            ),
            63 => 
            array (
                'id' => 64,
                'title' => 'F0F335DB-34EC-89BB-EE30-014B4844D43E',
                'slug' => 'f0f335db-34ec-89bb-ee30-014b4844d43e',
                'hasTitle' => 0,
                'isGuest' => 1,
                'template_id' => '475',
                'user_id' => NULL,
                'body' => NULL,
                'image' => 'F0F335DB-34EC-89BB-EE30-014B4844D43E.png',
                'isPublished' => 0,
                'source' => NULL,
                'website' => NULL,
                'created_at' => '2019-03-26 05:32:39',
                'updated_at' => '2019-03-26 05:32:39',
            ),
        ));
        
        
    }
}